[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
STREAMLIT_SERVER_HEADLESS = "true"

# These will be set as environment variables in Railway dashboard
# GEMINI_API_KEY = "your-gemini-api-key"
# OPENAI_API_KEY = "your-openai-api-key"
# AWS_ACCESS_KEY_ID = "your-aws-access-key"
# AWS_SECRET_ACCESS_KEY = "your-aws-secret-key" 